name: dds
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.7.7
  - tensorflow-gpu=1.14
  - flask
  - munch
  - networkx
  - pyyaml
  - requests
  - pytorch
  - pandas
  - pillow
  - pip
  - pip:
    - opencv-contrib-python
    - ultralytics
    - seaborn>=0.11.0
    - psutil
    - py-cpuinfo
    - filelock

